machine:
  pre:
    - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
  java:
    version: oraclejdk8
  services:
    - docker

dependencies:
  override:

test:
    override:
        - docker pull espirado/lncrna_annotation
        - curl -fsSL get.nextflow.io | bash
        - ./nextflow run . -profile test