
machine:
  java:
    version: openjdk8
  services:
    - docker

test:
    override:
        - docker pull espirado/lncrna_annotation
        - curl -fsSL get.nextflow.io | bash
        - ./nextflow run . -profile test